title: Matt Latourelle Music
description: Official music site
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  music:
    output: false
