title: Matt Latourelle Music
description: Official music site
baseurl: ""
url: "https://mlato.github.io/"

# Build settings
theme: jekyll-theme-minimal

# Collections
collections:
  music:
    output: false
